name:summa

on:
  push:
    branches:
      -master
  
  
  workflow_dispatch:


jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        -name: summa
         run: echo "i am happy"

    deploy:
      runs-on: ubuntu-latest

      steps:
        -name: deploy
         run: echo "i am deply"













